export const conventionRoutes = {
  exclude: [
    /\/components\/?/,
    /\/models\/?/,
    /\/constants\/?/,
    /\/configs\/?/,
    /\/assets\/?/,
    /\/domains\/?/,
    /\/executors\/?/,
    /\/*\.executors\/?/,
    /\/effects\/?/,
    /\/helps\/?/,
    /\/helpers\/?/,
    /\/hooks\/?/,
    /\/layouts\/?/,
    /\/typings\/?/,
    /\/utils\/?/,
    /\/wrappers\/?/,
    /\/services\/?/,
    /\.md$/,
    /_/,
    /[A-Z]/,
  ],
};
