// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useEffect } from 'react';
import { executors as rawExecutors } from './executors';

const Executor = React.memo(
  ({ hook, namespace }: { hook: () => any; namespace: string }) => {
    hook();

    useEffect(() => {
      console.log('executor: ', namespace, ' mounted.');
      return () => {
        console.log('executor: ', namespace, ' unmounted.');
      };
    }, []);

    return null;
  },
);

export default React.memo(() => {
  return (
    <>
      {rawExecutors.map((item) => (
        <Executor
          key={item.namespace}
          hook={item.executor}
          namespace={item.namespace}
        />
      ))}
    </>
  );
});
